### ISSUE TITLE
Merging 2  pdf with each of 3 mb get error

### ISSUE THREAD

**Issue by harsh049** [karuppiah7890/easy-pdf-merge#11]
OS: Windows 10
node : 8.12

whenever i merge 2 pdf file of each 3 mb i get below error 

Command failed: java -jar "C:\nokia\pdf_production\Development\nokia-pdf-production\node_modules\easy-pdf-merge\jar\pdfbox.jar" PDFMerger "C:\nokia\pdf_production\Development\nokia-pdf-production\output/doc43_1.pdf" "C:\nokia\pdf_production\Development\nokia-pdf-production\output/doc43_2.pdf" "C:\nokia\pdf_production\Development\nokia-pdf-production\output/doc43.pdf"
Nov 03, 2018 11:29:08 PM org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB suggestKCMS
INFO: To get higher rendering speed on java 8 oder 9,
Nov 03, 2018 11:29:08 PM org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB suggestKCMS
INFO:   use the option -Dsun.java2d.cmm=sun.java2d.cmm.kcms.KcmsServiceProvider
Nov 03, 2018 11:29:08 PM org.apache.pdfbox.pdmodel.graphics.color.PDDeviceRGB suggestKCMS
INFO:   or call System.setProperty("sun.java2d.cmm", "sun.java2d.cmm.kcms.KcmsServiceProvider")
Exception in thread "main" java.lang.StackOverflowError
        at java.util.HashMap.get(Unknown Source)
        at org.apache.pdfbox.multipdf.PDFCloneUtility.cloneForNewDocument(PDFCloneUtility.java:78)
        at org.apache.pdfbox.multipdf.PDFCloneUtility.cloneForNewDocument(PDFCloneUtility.java:101)
        at org.apache.pdfbox.multipdf.PDFCloneUtility.cloneForNewDocument(PDFCloneUtility.java:140)
        at org.apache.pdfbox.multipdf.PDFCloneUtility.cloneForNewDocument(PDFCloneUtility.java:101)
        at org.apache.pdfbox.multipdf.PDFCloneUtility.cloneForNewDocument(PDFCloneUtility.java:140)
        at org.apache.pdfbox.multipdf.PDFCloneUtility.cloneForNewDocument(PDFCloneUtility.java:101)
        at org.apache.pdfbox.multipdf.PDFCloneUtility.cloneForNewDocument(PDFCloneUtility.java:140)

**Comment by g0ddish** [comment]
#13 should solve this
