### ISSUE TITLE
Merging problem error with java -jar

### ISSUE THREAD

**Issue by AshwanthMadhav** [karuppiah7890/easy-pdf-merge#33]
Error when merging is

Unhandled error for request GET /api/survey/roadmapPdf?surveyId=60928c68791bbf2fee0317e1&access_token=3sk1enF2m1QX2jbjW2Eirq7j3Qu2Rm2pv43LeIiyfPOpdf6nSnzpDUt26TJ0Sc7A: Error: Command failed: java -jar /Users/ashwanthmadhav/Documents/projects/ongoing/dne/udx-china/node_modules/easy-pdf-merge/jar/pdfbox.jar PDFMerger "/tmp/dne/60928c68791bbf2fee0317e1/j440wf9avl.pdf" "/tmp/dne/60928c68791bbf2fee0317e1/60928c68791bbf2fee0317e1_roadMapGenerated.pdf" "/tmp/dne/60928c68791bbf2fee0317e1/7filimby30.pdf"
Exception in thread "main" java.io.IOException: Error: End-of-File, expected line
	at org.apache.pdfbox.pdfparser.BaseParser.readLine(BaseParser.java:1103)
	at org.apache.pdfbox.pdfparser.COSParser.parseHeader(COSParser.java:2581)
	at org.apache.pdfbox.pdfparser.COSParser.parsePDFHeader(COSParser.java:2560)
	at org.apache.pdfbox.pdfparser.PDFParser.parse(PDFParser.java:219)
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1099)
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1082)
	at org.apache.pdfbox.pdmodel.PDDocument.load(PDDocument.java:1006)
	at org.apache.pdfbox.multipdf.PDFMergerUtility.legacyMergeDocuments(PDFMergerUtility.java:451)
	at org.apache.pdfbox.multipdf.PDFMergerUtility.mergeDocuments(PDFMergerUtility.java:346)
	at org.apache.pdfbox.tools.PDFMerger.merge(PDFMerger.java:70)
	at org.apache.pdfbox.tools.PDFMerger.main(PDFMerger.java:49)
	at org.apache.pdfbox.tools.PDFBox.main(PDFBox.java:81)

    at ChildProcess.exithandler (child_process.js:308:12)
    at ChildProcess.emit (events.js:315:20)
    at ChildProcess.EventEmitter.emit (domain.js:467:12)
    at maybeClose (internal/child_process.js:1048:16)
    at Socket.<anonymous> (internal/child_process.js:439:11)
    at Socket.emit (events.js:315:20)
    at Socket.EventEmitter.emit (domain.js:467:12)
    at Pipe.<anonymous> (net.js:673:12)

ALready installed java and it was working fine beofre some months ago.

Now getting this error.

**Comment by karuppiah7890** [comment]
Hi ! Thanks for reporting the issue! Unfortunately I currently don't have the bandwidth to checkout the issues currently. PRs are welcome!
