### ISSUE TITLE
Issue with Merging Editable PDF

### ISSUE THREAD

**Issue by Salesforce-Techie** [karuppiah7890/easy-pdf-merge#36]
Error: Command failed: java -jar /app/node_modules/easy-pdf-merge/jar/pdfbox.jar PDFMerger "/app/finalpdf/2021-27-060927GarroneDarcyRecertificationApprovedCombined/merged.pdf" "/app/finalpdf/2021-27-060927GarroneDarcyRecertificationApprovedCombined/a393g000000RaAiAAK.pdf" "/app/finalpdf/2021-27-060927GarroneDarcyRecertificationApprovedCombined/a393g000000ReDfAAK.pdf" "/app/finalpdf/2021-27-060927GarroneDarcyRecertificationApprovedCombined/a393g000000RaBbAAK.pdf" "/app/finalpdf/2021-27-060927GarroneDarcyRecertificationApprovedCombined/a393g000000RaDDAA0.pdf" "/app/finalpdf/2021-27-060927GarroneDarcyRecertificationApprovedCombined/a393g000000RaDIAA0.pdf" "/app/finalpdf/2021-27-060927GarroneDarcyRecertificationApprovedCombined/merged.pdf"
Picked up JAVA_TOOL_OPTIONS: -Xmx300m -Xss512k -XX:CICompilerCount=2 -Dfile.encoding=UTF-8 -javaagent:/app/.heroku/bin/heroku-metrics-agent.jar 
Aug 06, 2021 1:27:56 PM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider loadDiskCache
WARNING: New fonts found, font cache will be re-built
Aug 06, 2021 1:27:56 PM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Building on-disk font cache, this may take a while
Aug 06, 2021 1:27:56 PM org.apache.pdfbox.pdmodel.font.FileSystemFontProvider <init>
WARNING: Finished building on-disk font cache, found 76 fonts
Exception in thread "main" java.lang.ClassCastException: org.apache.pdfbox.cos.COSName cannot be cast to org.apache.pdfbox.cos.COSString
	at org.apache.pdfbox.pdmodel.interactive.form.PDVariableText.getDefaultAppearanceString(PDVariableText.java:91)
	at org.apache.pdfbox.pdmodel.interactive.form.AppearanceGeneratorHelper.<init>(AppearanceGeneratorHelper.java:114)
	at org.apache.pdfbox.pdmodel.interactive.form.PDTextField.constructAppearances(PDTextField.java:263)
	at org.apache.pdfbox.pdmodel.interactive.form.PDAcroForm.refreshAppearances(PDAcroForm.java:327)
	at org.apache.pdfbox.pdmodel.fixup.processor.AcroFormGenerateAppearancesProcessor.process(AcroFormGenerateAppearancesProcessor.java:54)
	at org.apache.pdfbox.pdmodel.fixup.AcroFormDefaultFixup.apply(AcroFormDefaultFixup.java:56)
	at org.apache.pdfbox.pdmodel.PDDocumentCatalog.getAcroForm(PDDocumentCatalog.java:132)
	at org.apache.pdfbox.pdmodel.PDDocumentCatalog.getAcroForm(PDDocumentCatalog.java:113)
	at org.apache.pdfbox.multipdf.PDFMergerUtility.appendDocument(PDFMergerUtility.java:519)
	at org.apache.pdfbox.multipdf.PDFMergerUtility.legacyMergeDocuments(PDFMergerUtility.java:459)
	at org.apache.pdfbox.multipdf.PDFMergerUtility.mergeDocuments(PDFMergerUtility.java:346)
	at org.apache.pdfbox.tools.PDFMerger.merge(PDFMerger.java:70)
	at org.apache.pdfbox.tools.PDFMerger.main(PDFMerger.java:49)
	at org.apache.pdfbox.tools.PDFBox.main(PDFBox.java:81)

**Comment by karuppiah7890** [comment]
I don't have the bandwidth to checkout the issues currently. PRs are welcome!
